language: java

env:
  global:
   - secure: "D69O3Ujw21aGcVCjQTzpGmn0Oew6yOo0Eu+gfH0dmmaPi8XUKsAwx7x8c8F4beYhunDQr7JWIh1TjvFcJy6+4+pLsMkI74l3Zl+4v/TxEv+L2l4VBLDrDbsCxQOLyxP/MZfXzEQH7gPs6+ouPqbrn8rGp99pndzhot8bxPKYc4akL3PDvf80WtA5KcYwOZbhcgw2qXZMl3QzeSZJfIdZs2/iH0rRPQXOClwjMFebsb/rOdpRV7cSibSkrQJEs+V/RPLVHfNfSfzeZGZ/iBDJlPE+bcSdsVBqejPHKWdm5Lgzb62lGi9Pfnc8WoFKGJ9sYoSBHgBeNoJfwF7OnfLNHdrRSdf9UOFHOGBw+a0nAY83vmPcNALbi3AhGr5HE59gE39UFMRtv+WQ1Uxubv0KOwVhZY1M2JRLlDyaWzSSkUFUVUkbaFwzYOkHjoWlu7PRAN80OYRLQMTkU4K2M2JfkrAcY4P8N1jTriGa2np0hOJS6rXH+DREFM91Lm6gV9Pr2UkgEgYj/DAFlttn0MgX3wlXCdFEsrIfVBN4EF4O4kWWXmo33qmgRNbshOrgQsmIT3LRrWVwlcJyFR3uEXS/BjwrWQruwUbY26tKoZKGot9j//KGONAWXWaTvbC3lqmJVrd3P2o9Q/n5i2XTlLyxRL+CCm1/VBPAblJmnBHF7ng="
   - secure: "k5wZXBRnkHlL/z4CRJmyoaQn7gzz/oyig9pIWpczyLrx7EpoOJ4CGZ8cBz+sgEY0d+ZKr4OtxYbNJeVl7Fo7uU4C2lKksv5/9fkuWUICizG0fSMrmAPbx0pF41KkkMXxjpx9eIM8UVkEgplZTuhzo0TRZSj6VEfoNZhuQB+l0WzepSL8+ctxSscpNtusCc/xhl7JNhOrANgaBVv7PQLI5Zd2AUDCNxDaBG2h2l86ihWa9hTOsajfqcxMzAMsN8v6aBmpy6D28veZCR7ockb1ojV2rKykF8zkjnmK65qS0aP6DEr9c9/C+yKn84M/8FOH+vvLjrat5MSNUYq4mgOmtPAF3/t+OnT1wqjdMN0XDx2ahq/oyzNFlGzRlZAj8gfctw3IVvVgD4aLGtUg2+/D8WkhsIzsp5Kysm+sqDURZXXxGdUPQPJoR3kATzHhjliMYL9eLgiepfpNju7gB2+wPwOdXjjSpqXaceQRDhxghnKvdo5Kj58uHaT0UHwnRb5sj0MftlCigPqzXXgdBsyyJl+LpkzKfDyDAewYmdjguc1qtA4L+pb8L51UlaBuRAloodLAPblJOm/lxLhL1aGM8fLK9cse4dPgpF4XOioi/FIzEhkL4Nc3vuxZ9vJLLheKivM6dwYIYN3uwt2rLshBZs5JEzSSRcpBY/OwvhsR4rw="
   
jdk:
  - oraclejdk8
  
cache:
  directories:
  - $HOME/.m2
  
install: true

script: 
    - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true

after_success:
  - mvn test jacoco:report coveralls:report -DrepoToken=$COVERALLS_TOKEN
  - mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DapiToken=$CODACY_PROJECT_TOKEN