version: "2"

services:

  # Docker image for the P6
  p6:
    image: lorislab/p6
    environment:
        DB_URL: jdbc:postgresql://postgresdb:5432/p6
        DB_USER: p6
        DB_PWD: p6
    ports: 
        - "8080:8080"
    restart: on-failure
    networks:
     - p6

  # PostgresSQL database
  postgresdb:
    image: postgres:11.1
    ports:
        - "5432:5432"
    command: postgres -c max_prepared_transactions=100
    volumes:
        - ./src/main/docker/db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
       POSTGRES_PASSWORD: p6
    networks:
     - p6

networks:
    p6:
